### PR TITLE
Adding overflow trumps.

### PR DESCRIPTION
**Pull request by tomgenoni**
Adding overflow-x: auto; and overflow-y: auto;

### CODE REVIEW

**Comment by danoc** [comment]
LGTM.

**Comment by danoc** [comment]
Actually this should be a `Feature`, not a `Patch`.

**Comment by tomgenoni** [comment]
Why Feature? These did not exist before.

**Comment by danoc** [comment]
I did a little research today to understand the difference, and basically:

> Patch version Z (x.y.Z | x > 0) **MUST be incremented if only backwards compatible bug fixes are introduced**. A bug fix is defined as an internal change that fixes incorrect behavior.
>
> Feature version Y (x.Y.z | x > 0) **MUST be incremented if new, backwards compatible functionality is introduced to the public API**. It MUST be incremented if any public API functionality is marked as deprecated. It MAY be incremented if substantial new functionality or improvements are introduced within the private code. It MAY include patch level changes. Patch version MUST be reset to 0 when minor version is incremented.

There's a bunch that we mislabeled, but I'll update `CONTRIBUTING.md` to make this more clear.

**Pull request merged**
