### PR TITLE
Adding consistent disabled states for inputs.

### PR DESCRIPTION
**Pull request by tomgenoni**
See https://jsfiddle.net/rxu4empz/1/ for examples.

### CODE REVIEW

**Comment by tomgenoni** [comment]
@danoc Note that I removed the class referenced in https://github.com/optimizely/lego/issues/117

**Comment by danoc** [comment]
Are you saying you removed the `.lego-input--disabled` class?

**Comment by tomgenoni** [comment]
yes I removed `.lego-input--disabled`.

**Comment by danoc** [comment]
Cool let's make this a release then since it's a breaking change.

**Comment by danoc** [comment]
Actually, would it just work the same with the new Sass? As in everything that had `.lego-input--disabled` will still keep the same styles?

**Comment by tomgenoni** [comment]
It might but I want to keep the naming consistent.

**Comment by danoc** [comment]
Ok cool LGTM.

**Pull request merged**
