### PR TITLE
Tom/border trumps

### PR DESCRIPTION
**Pull request by tomgenoni**
@danoc I also updated the steps in CONTRIBUTING.md so that "Open a pull request against `master`. Add at least one reviewer." is the last instruction.

### CODE REVIEW

**Comment by danoc** [comment]
Great, thanks @tomgenoni. Feel free to merge whenever but just know that merging it will block our products from getting future minor and feature updates until we make changes to support this.

I'd recommend waiting to merge it next week once we make many breaking changes at once.

**Comment by tomgenoni** [comment]
Sure. This can wait.

**Comment by danoc** [comment]
What was the reasoning for this again? Anyways, LGTM.

**Comment by tomgenoni** [comment]
Because they come earlier in the CSS I wanted these classes to reliably apply since they effectively trumps.

**Pull request merged**
