### PR TITLE
refactor form label optional to not use pseudo element content

### PR DESCRIPTION
**Pull request by tscanlin**
@tomgenoni This is to address this JIRA ticket for i18n: https://optimizely.atlassian.net/browse/UXD-72

There are only about a dozen places this is used in the product and I can make a PR there as well to accompany this.

Just wanted to check and see if this is an ok way to address or if you'd prefer a different approach. This is also pretty similar to the .tagger class and I'm wondering if we would want to consolidate and make something like '.deemphasized-note' (terrible name, I know..) or something along those lines.

Let me know if you have ideas around this.

### CODE REVIEW

**Comment by tomgenoni** [comment]
This looks fine. Should I wait to merge until after the A/B PR is ready?

Also, regarding the `.tagger` class... it may be the same now but I'd prefer not to consolidate as the styling could eventually change and, semantically, it's nice to have different classes even though they may be applying the same styling. `text--right` and `numerical` do the same things but in tables its nice (IMHO) to have a separate, more meaningful class to use there.

**Comment by tscanlin** [comment]
Yeah, lets wait until I get that PR ready to go before merging this. I'll link to it here when it's good to go. Agree with you about keeping the classes separate for semantics purposes.

**Comment by tscanlin** [comment]
Opened a pr/diff for the product changes:
https://phabricator.optimizely.com/D4527

Please review when convenient @tomgenoni no rush

**Comment by tomgenoni** [comment]
LGTM

**Comment by 4vanger** [comment]
can you merge it please so we can close https://optimizely.atlassian.net/browse/UXD-72 and https://optimizely.atlassian.net/browse/INTL-357

**Pull request merged**
