### PR TITLE
add user list icon

### PR DESCRIPTION
**Pull request by LindaHong**
@tomgenoni @tscanlin adding user list icon.

### CODE REVIEW

**Comment by tomgenoni** [comment]
@tscanlin The `gulp svg` task is still there so you can output the sprite just as before.

**Comment by tscanlin** [comment]
@tomgenoni thanks for the reminder on that one. I tried running it and I'm seeing that some of the svg's have weird dimensions, see:
```
<symbol id="redo" viewBox="-471 274 16 14">
      <g><path d="M-455.7 279l-3.7 3.6c-.2.2-.4.2-.6.1-.2-.1-.3-.2-.3-.4v-7.4c0-.2.1-.4.3-.4.2-.1.4 0 .6.1l3.7 3.6c.1.1.2.2.2.4-.1.1-.1.2-.2.4"/><path d="M-465.9 277.8h8.9v1.6h-8.9c-1.7 0-3 1.3-3 3v.4c0 1.6 1.4 3 3 3h1.8c.4 0 .8.3.8.8 0 .4-.4.8-.8.8h-1.8c-2.6 0-4.6-2-4.6-4.5v-.4c-.1-2.7 2-4.7 4.6-4.7"/></g>
    </symbol>
    <symbol id="refresh" viewBox="0 0 32 32">
      <path d="M24.6 9.5l-2.2 2.2c.7 1.2 1.1 2.5 1.1 3.9 0 4.3-3.5 7.8-7.8 7.8s-7.8-3.5-7.8-7.8 3.5-7.8 7.8-7.8h.3V13l4.7-4.7 1.6-1.6L16 .5v4.4h-.3C9.8 4.9 5 9.7 5 15.6c0 5.9 4.8 10.8 10.8 10.8 5.9 0 10.8-4.8 10.8-10.8-.1-2.2-.8-4.4-2-6.1z"/>
    </symbol>
    <symbol id="save" viewBox="-472 273 15 16">
      <g><path d="M-458.9 273.9v6H-470v-6h-1.7v13.4c0 .5.4.9.9.9h12.6c.5 0 .9-.4.9-.9v-11.8l-1.6-1.6"/><path d="M-463 273.9h2.4v4.8h-2.4v-4.8z"/></g>
    </symbol>
```

Have you run into that before? Let me know if you have any ideas how to fix..

**Comment by tomgenoni** [comment]
@tscanlin Is there a problem with the icon? If the icon is aligned to the pixel grid you can get odd values.

**Comment by tscanlin** [comment]
The user list icon is fine, its some of the other icons that seem to have weird coordinates. But I'll probably just copy the code for the user list icon instead of all of them until I have time to dig into it a bit more.

**Pull request merged**
