### PR TITLE
popover fix

### PR DESCRIPTION
**Pull request by kwalker3690**
@danoc This coincides with the work done on the guiders

### CODE REVIEW

**Comment by tomgenoni** [comment]
@kwalker3690 Did @danoc go over the new versioning/change process?

**Comment by kwalker3690** [comment]
@tomgenoni yep, just added my change to the change log

**Comment by danoc** [comment]
@kwalker3690 – Can you clarify the text in the in the Markdown so that someone without context could also understand the change? Normally we would link to the issue so it provides context, but there is no issue in this case. Also, when referencing classes, can you use Markdown to format it like `.class-name`? Just clarifies things a bit.

Your change also caused a linter error. Click on "Details" on the PR page in GitHub to see the console output.

**Comment by danoc** [comment]
LGTM.

**Pull request merged**
